<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class FieldOfficerSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $fieldOfficers = [
            [
                'municipality_id' => 1,
                'fname' => 'Sarah Kristina',
                'mid_initial' => 'G',
                'lname' => 'Romanillos',
                'position' => 'LGOO V',
                'cluster' => "D'ONE",
                'profile_img' => null,
            ],
            [
                'municipality_id' => 2,
                'fname' => 'Michael',
                'mid_initial' => 'B',
                'lname' => 'Cabanag',
                'position' => 'LGOO VI',
                'cluster' => 'M&M',
                'profile_img' => null,
            ],
            [
                'municipality_id' => 3,
                'fname' => 'Drib Laurence',
                'mid_initial' => 'B',
                'lname' => 'Ingles',
                'position' => 'LGOO VI',
                'cluster' => 'M&M',
                'profile_img' => null,
            ],
            [
                'municipality_id' => 4,
                'fname' => 'Victor Jr.',
                'mid_initial' => 'S',
                'lname' => 'Lapiz',
                'position' => 'LGOO VI',
                'cluster' => "D'ONE",
                'profile_img' => null,
            ],
            [
                'municipality_id' => 5,
                'fname' => 'Emmylou',
                'mid_initial' => 'F',
                'lname' => 'Rama',
                'position' => 'LGOO VI',
                'cluster' => "D'ONE",
                'profile_img' => null,
            ],
            [
                'municipality_id' => 6,
                'fname' => 'Florencio Jr.',
                'mid_initial' => 'V',
                'lname' => 'Halasan',
                'position' => 'LGOO VI',
                'cluster' => "D'ONE",
                'profile_img' => null,
            ],
            [
                'municipality_id' => 7,
                'fname' => 'Adonis',
                'mid_initial' => 'R',
                'lname' => 'Damalerio',
                'position' => 'LGOO VI',
                'cluster' => 'M&M',
                'profile_img' => null,
            ],
            [
                'municipality_id' => 8,
                'fname' => 'Jun Ian',
                'mid_initial' => 'A',
                'lname' => 'Suric',
                'position' => 'LGOO VI',
                'cluster' => 'M&M',
                'profile_img' => null,
            ],
            [
                'municipality_id' => 9,
                'fname' => 'Nicanor',
                'mid_initial' => 'P',
                'lname' => 'Bungabong',
                'position' => 'LGOO VI',
                'cluster' => 'M&M',
                'profile_img' => null,
            ],
            [
                'municipality_id' => 10,
                'fname' => 'Rhea Joy',
                'mid_initial' => 'O',
                'lname' => 'Figueroa',
                'position' => 'LGOO VI',
                'cluster' => "D'ONE",
                'profile_img' => null,
            ],
            [
                'municipality_id' => 11,
                'fname' => 'Jose Jekeri',
                'mid_initial' => 'P',
                'lname' => 'Taningco',
                'position' => 'LGOO VI',
                'cluster' => "D'ONE",
                'profile_img' => null,
            ],
            [
                'municipality_id' => 12,
                'fname' => 'Judy Grace',
                'mid_initial' => 'R',
                'lname' => 'Dominguez',
                'position' => 'LGOO VI',
                'cluster' => 'M&M',
                'profile_img' => null,
            ],
            [
                'municipality_id' => 13,
                'fname' => 'Niña Christine',
                'mid_initial' => 'P',
                'lname' => 'Montejo',
                'position' => 'LGOO VI',
                'cluster' => 'M&M',
                'profile_img' => null,
            ],
            [
                'municipality_id' => 14,
                'fname' => 'Jennifer',
                'mid_initial' => 'P',
                'lname' => 'Amihan',
                'position' => 'LGOO VI',
                'cluster' => "D'ONE",
                'profile_img' => null,
            ],
            [
                'municipality_id' => 15,
                'fname' => 'Jogepons',
                'mid_initial' => 'A',
                'lname' => 'Ruloma',
                'position' => 'LGOO VI',
                'cluster' => "D'ONE",
                'profile_img' => null,
            ],
            [
                'municipality_id' => 16,
                'fname' => 'Josie',
                'mid_initial' => 'M',
                'lname' => 'Montes',
                'position' => 'LGOO VI',
                'cluster' => "D'ONE",
                'profile_img' => null,
            ],
            [
                'municipality_id' => 17,
                'fname' => 'Redemcion',
                'mid_initial' => 'G',
                'lname' => 'Cag-ong',
                'position' => 'LGOO VI',
                'cluster' => "D'ONE",
                'profile_img' => null,
            ],
            [
                'municipality_id' => 18,
                'fname' => 'Wilfrans',
                'mid_initial' => 'B',
                'lname' => 'Bangalao',
                'position' => 'LGOO VI',
                'cluster' => 'M&M',
                'profile_img' => null,
            ],
            [
                'municipality_id' => 19,
                'fname' => 'Norman',
                'mid_initial' => 'L',
                'lname' => 'Ali',
                'position' => 'LGOO VI',
                'cluster' => "D'ONE",
                'profile_img' => null,
            ],
            [
                'municipality_id' => 20,
                'fname' => 'Ma. Sharon',
                'mid_initial' => 'M',
                'lname' => 'Halasan',
                'position' => 'LGOO VI',
                'cluster' => "D'ONE",
                'profile_img' => null,
            ],
            [
                'municipality_id' => 21,
                'fname' => 'Elvira',
                'mid_initial' => 'B',
                'lname' => 'Mandin',
                'position' => 'LGOO VI',
                'cluster' => 'M&M',
                'profile_img' => null,
            ],
            [
                'municipality_id' => 22,
                'fname' => 'Maria Luz',
                'mid_initial' => 'E',
                'lname' => 'Lintua',
                'position' => 'LGOO VI',
                'cluster' => 'M&M',
                'profile_img' => null,
            ],
            [
                'municipality_id' => 23,
                'fname' => 'Ismael Vincent',
                'mid_initial' => 'T',
                'lname' => 'Igcalinos',
                'position' => 'LGOO VI',
                'cluster' => 'M&M',
                'profile_img' => null,
            ],
            [
                'municipality_id' => 24,
                'fname' => 'Maura',
                'mid_initial' => 'M',
                'lname' => 'Justol',
                'position' => 'LGOO VI',
                'cluster' => "D'ONE",
                'profile_img' => null,
            ],
            [
                'municipality_id' => 25,
                'fname' => 'Eunice Anne',
                'mid_initial' => 'C',
                'lname' => 'Boniel',
                'position' => 'LGOO VI',
                'cluster' => 'M&M',
                'profile_img' => null,
            ],
            [
                'municipality_id' => 26,
                'fname' => 'Jayson',
                'mid_initial' => 'B',
                'lname' => 'Tumale',
                'position' => 'LGOO VI',
                'cluster' => "D'ONE",
                'profile_img' => null,
            ],
            [
                'municipality_id' => 27,
                'fname' => 'Anthony Dei',
                'mid_initial' => 'V',
                'lname' => 'Dalida',
                'position' => 'LGOO VI',
                'cluster' => 'M&M',
                'profile_img' => null,
            ],
            [
                'municipality_id' => 28,
                'fname' => 'Fidel',
                'mid_initial' => 'M',
                'lname' => 'Narisma',
                'position' => 'LGOO VI',
                'cluster' => 'M&M',
                'profile_img' => null,
            ],
            [
                'municipality_id' => 29,
                'fname' => 'Mary Ann',
                'mid_initial' => 'A',
                'lname' => 'Verga',
                'position' => 'LGOO VI',
                'cluster' => 'M&M',
                'profile_img' => null,
            ],
            [
                'municipality_id' => 30,
                'fname' => 'Jocelyn',
                'mid_initial' => 'B',
                'lname' => 'Bandala',
                'position' => 'LGOO VI',
                'cluster' => 'M&M',
                'profile_img' => null,
            ],
            [
                'municipality_id' => 31,
                'fname' => 'Glenda',
                'mid_initial' => 'A',
                'lname' => 'Laude',
                'position' => 'LGOO VI',
                'cluster' => "D'ONE",
                'profile_img' => null,
            ],
            [
                'municipality_id' => 32,
                'fname' => 'Ana Theresa',
                'mid_initial' => 'G',
                'lname' => 'Rasonabe',
                'position' => 'LGOO VI',
                'cluster' => 'M&M',
                'profile_img' => null,
            ],
            [
                'municipality_id' => 33,
                'fname' => 'Corazon',
                'mid_initial' => 'C',
                'lname' => 'Evangelista',
                'position' => 'LGOO VI',
                'cluster' => "D'ONE",
                'profile_img' => null,
            ],
            [
                'municipality_id' => 34,
                'fname' => 'Cecilio',
                'mid_initial' => 'S',
                'lname' => 'Nisnisan',
                'position' => 'LGOO VI',
                'cluster' => "D'ONE",
                'profile_img' => null,
            ],
            [
                'municipality_id' => 35,
                'fname' => 'Nilda',
                'mid_initial' => 'P',
                'lname' => 'Unajan',
                'position' => 'LGOO VI',
                'cluster' => 'M&M',
                'profile_img' => null,
            ],
            [
                'municipality_id' => 36,
                'fname' => 'Rachel',
                'mid_initial' => 'S',
                'lname' => 'Torremocha',
                'position' => 'LGOO VI',
                'cluster' => 'M&M',
                'profile_img' => null,
            ],
            [
                'municipality_id' => 37,
                'fname' => 'Dyosa Marie',
                'mid_initial' => 'P',
                'lname' => 'Cosare',
                'position' => 'LGOO VI',
                'cluster' => "D'ONE",
                'profile_img' => null,
            ],
            [
                'municipality_id' => 38,
                'fname' => 'Mona Lissa',
                'mid_initial' => 'T',
                'lname' => 'Hinog',
                'position' => 'LGOO VI',
                'cluster' => "D'ONE",
                'profile_img' => null,
            ],
            [
                'municipality_id' => 39,
                'fname' => 'Lindsey Marie',
                'mid_initial' => 'A',
                'lname' => 'Vismanos',
                'position' => 'LGOO VI',
                'cluster' => "D'ONE",
                'profile_img' => null,
            ],
            [
                'municipality_id' => 40,
                'fname' => 'Christine Rose',
                'mid_initial' => 'F',
                'lname' => 'Cagampang',
                'position' => 'LGOO VI',
                'cluster' => 'M&M',
                'profile_img' => null,
            ],
            [
                'municipality_id' => 41,
                'fname' => 'Hyacinth',
                'mid_initial' => 'P',
                'lname' => 'Garrote',
                'position' => 'LGOO VI',
                'cluster' => 'M&M',
                'profile_img' => null,
            ],
            [
                'municipality_id' => 42,
                'fname' => 'Ted',
                'mid_initial' => 'N',
                'lname' => 'Mascariñas',
                'position' => 'LGOO VI',
                'cluster' => "D'ONE",
                'profile_img' => null,
            ],
            [
                'municipality_id' => 43,
                'fname' => 'Lee Joshua',
                'mid_initial' => 'A',
                'lname' => 'Kaindoy',
                'position' => 'ADA IV',
                'cluster' => "D'ONE",
                'profile_img' => null,
            ],
            [
                'municipality_id' => 43,
                'fname' => 'Juliet',
                'mid_initial' => 'C',
                'lname' => 'Olalo',
                'position' => 'LGOO VI',
                'cluster' => "D'ONE",
                'profile_img' => null,
            ],
            [
                'municipality_id' => 44,
                'fname' => 'Lady Lennoire',
                'mid_initial' => 'P',
                'lname' => 'Abad',
                'position' => 'LGOO VI',
                'cluster' => "D'ONE",
                'profile_img' => null,
            ],
            [
                'municipality_id' => 45,
                'fname' => 'Rhoel',
                'mid_initial' => 'A',
                'lname' => 'Tumarao',
                'position' => 'LGOO VI',
                'cluster' => "D'ONE",
                'profile_img' => null,
            ],
            [
                'municipality_id' => 46,
                'fname' => 'Angelo',
                'mid_initial' => 'S',
                'lname' => 'Mahinay',
                'position' => 'LGOO VI',
                'cluster' => "D'ONE",
                'profile_img' => null,
            ],
            [
                'municipality_id' => 47,
                'fname' => 'Karen Ann',
                'mid_initial' => 'B',
                'lname' => 'Beniga',
                'position' => 'LGOO V',
                'cluster' => 'M&M',
                'profile_img' => null,
            ],
            [
                'municipality_id' => 48,
                'fname' => 'Jose Ruben',
                'mid_initial' => 'H',
                'lname' => 'Racho',
                'position' => 'LGOO VI',
                'cluster' => 'M&M',
                'profile_img' => null,
            ],
        ];

        DB::table('field_officers')->insert($fieldOfficers);
    }
}
